version: "3.3"
services:

  mysql-database:
    build: mysql-image/
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: airport

  postgres-database:
    build: postgres-image/
    ports:
      - 54321:5432

  jdbc-connector:
    build: ../
    ports:
      - 50051:50051
    environment:
      DATABASE_FETCH_SIZE: 100000
      MAX_DATA_CHUNK_SIZE: 300

  qix-engine:
    container_name: qix-engine
    image: qlikcore/engine:12.321.0
    ports:
      - 19076:9076
    command: -S AcceptEULA=${ACCEPT_EULA} -S EnableGrpcCustomConnectors=1 -S GrpcConnectorPlugins="jdbc,jdbc-connector:50051"
